nrDocumento varchar(10) PRIMARY KEY,
	rilascio date,
	scadenza date,
	professione varchar(30) NOT NULL,
	nome varchar(10) NOT NULL,
	cognome varchar (15) NOT NULL,
	isPatente bool NOT NULL,
	luogoDiNascita varchar(20) NOT NULL,
	dataDiNascita date NOT NULL,
	CategoriaPatente char(1) NOT NULL,
	nazione varchar(20) NOT NULL,
	citta varchar(20) NOT NULL,
	cap numeric(5,0) NOT NULL,
	civico numeric(4,0) NOT NULL,
	via varchar(20) NOT NULL